server:
  port: 8080

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recipeUserProfile
      username: JavaUser
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  queueRegister: register-queue
  exchange: userprofile-exchange
  addressRegisterBindingKey: address-register-key
  queueAddressRegister: address-register-queue
  queueElasticRegister: elastic-register-queue
  elasticRegisterBindingKey: register-key



